### ISSUE TITLE
[Feature Request] Support .mj as a file extension for mojo.

### ISSUE THREAD

**Issue by LDJnr** [modular/modular#20]
## Request

 I think it would be a nice feature to have a 2 letter file extension supported, such as **.mj**, this would be supported of course alongside .mojo and 🔥 and does not need to replace either. 

### Motivation

I think this would be a good new file extension that supersedes the 2 letter file extensions people are used to typing and seeing with python such as **py**, it's also very efficient to type each, for example on a traditional keyboard, both the P and the Y keys are close to each other and both can be hit with the right hand quickly in succession. 

mj are 2 letters that are also in close proximity and both on the right half of the traditional keyboard, making it quick and efficient to type, just as much or more than **py** is.

It also follows the theme of removing the vowels to create shorter file extensions, for example:

Ruby is supported as it's vowel-less version: **rb**

Other popular 2 character file extensions for programming languages:
Typescript: **ts**
Javascript:  **js**

and even a history of removing vowels for shortening, for non-programming language file types such as:
Jpeg gets turned into: **jpg**  
Mpeg gets turned into **mpg**

 Overall for both readability and practicality sake, if you were to make a file named **main.mojo**, then effectively half the file name you have to read or type out ends up being the extension itself, and sure there is another option which is 🔥, but I think on most desktops that is even more difficult and impractical to type out, since you need to open an emoji window or hotkey etc afaik

### Description and Requirements

TBD

**Comment by lattner** [comment]
The examples you cite (.jpg etc) go back to old dos/windows days which only supported 3 character extensions, but those days are over. and I have experience with the swift community using the .swift file extension - which was fine even though its 25% longer than mojo :). 

I personally don't think that this is something that we should do.  Supporting two different extensions is enough,  I don't think we should fragment things further.  Do you have additional rationale other than "some other older languages did it this way"?

**Comment by lattner** [comment]
cool, let's keep it simple and explicit.  Thanks for the feedback!

**Comment by southerndevz** [comment]
[LDJnr](https://github.com/LDJnr) has a valid point about the `.mj` extension. I heard of this Mojo from a YouTube podcast and thought it was a cool undertaking. However, ignoring developer requests just because you're used to it in Swift is not good practice especially when you want all your hard work to be adopted. Companies try as hard as they can to lure consumer into their products even by using shorter slogans and memorable phrases. So, rather than justifying the swifterization of python, just give devz a shorter extension. I hate the emoji extension as much as I hate writing `.mojo`

To add a 🔥 emoji I had to add an emoji keyboard and double-click Fn, wait for the emoji keyboard, search for _"fire"_,  it was even worse in Windows I had to press `Windows + .` and search for the 🔥 emoji after being disrupted by a sea of GIFs. 

I'm keen on trying this Mojo out but I'm worried that we can't offer any contributions thanks to our Swift overlords. Look, I'm a big fan of typed, being a C, C++, and Kotlin/Java programmer as well, however not listening to your devz is always a bad idea. We need a better extension than this joke. 

Please take this as constructive criticism. I like your objective but the extensions are not appealing.

**Comment by gryznar** [comment]
+1 for this

**Comment by lattner** [comment]
@southerndevz just to be clear, you can use .mojo if you'd prefer, no one is forcing the use of fire emoji as an extension.

**Comment by southerndevz** [comment]
`.mojo` is not appealing at all to tell you the truth. But if you're not ready to give this extension then that's fine.

**Comment by ksandvik** [comment]
I would think all two letter extensions and most likely three letter extensions are used by now. As a bonus, .mojo sounds like what its used for.
